# -*- coding: utf-8 -*-
"""FlowerspeciesClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/kirankamatmgm/FlowerImageClassifier/blob/master/FlowerspeciesClassifier.ipynb

We are going to use the [Oxford 102 Flower Dataset](http://www.robots.ox.ac.uk/~vgg/data/flowers/102/) by [Nilsback,M-E and Zisserman, A., 2008](http://www.robots.ox.ac.uk/~vgg/publications/papers/nilsback08.pdf). A 102 category dataset consisting of 102 flower categories, commonly occuring in the United Kingdom. Each class consists of 40 to 258 images. The images have large scale, pose and light variations.

Credits: fastai(for inspiring to do this project and ofcourse Im using fastai library)

To understand details about all basic code see my [1st Project](https://kirankamath.netlify.app/blog/image-classification-fast-ai/)
"""


# Commented out IPython magic to ensure Python compatibility.
# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from fastai import *
from fastai.basics import *
from fastai.vision import *
from fastai.metrics import *

from fastai.callbacks.hooks import *
from fastai.utils.mem import *

path=untar_data(URLs.FLOWERS)

path.ls()

path_img=path/'jpg'

"""This dataset is has train test and validation data in text file and images in jpg file. So using pandas dataframe looks good here"""

trn=pd.read_csv(path/'train.txt',sep=" ",header=None)
val=pd.read_csv(path/'valid.txt',sep=" ",header=None)
tst=pd.read_csv(path/'test.txt',sep=" ",header=None)
df = trn.append(val,ignore_index=True).append(tst,ignore_index=True)
df.columns=['Img','Class']
df.index=df.Img
df.head()

len(trn), len(val), len(tst)

"""We have images with format jpg/{some name}.jpg and class label. But we dont know the name of flower. So to know name of flower, we have 2 steps.
1.   create a dictionary and add it manually seeing dataset website, or use content.json available with label and flower name
2.   Use web scrapping to extract images name.

2nd option looks good, since it opportunity to learn web scrapping.
I am using BeautifulSoup


"""

from bs4 import BeautifulSoup
import re

url = 'http://www.robots.ox.ac.uk/~vgg/data/flowers/102/categories.html'
r= requests.get(url)

soup=BeautifulSoup(r.content, "lxml")
ims=soup.findAll('img')
print(ims)





"""Observe the content of ims carefully. It has img tag, in which we are interested in src and alt tag.
alt tag content label names, and src content details which we have in dataframe Img part.
so using this we can change df such that jpg/{something}.jpg is equal to label names
"""

sample = {}
for im in ims[0:]:
    sample[f"jpg/image_{im['src'].split('_')[-1]}"] = im['alt']
len(sample.keys()), {k: sample[k] for k in list(sample)[:5]}

"""We can see that its showing 102 keys means that we have scraped 102 image lables. There are 102 labels.

But actually we want dictionary that contains class label number to name mapping, so lets do that
"""

names = {}
for im in sample.keys():
  names[df.loc[im]['Class']]=sample[im]

{k: names[k] for k in list(names)[:5]}

"""Go through the labels once

"""

{k: names[k] for k in list(names)}

codes = np.array([names[i] for i in range(len(names))]); codes

"""Here many labels contain space in between so lets remove that"""

trn[trn.columns[-1]] = trn[trn.columns[-1]].apply(lambda x: codes[x].replace(' ','_'))
val[val.columns[-1]] = val[val.columns[-1]].apply(lambda x: codes[x].replace(' ','_'))
tst[tst.columns[-1]] = tst[tst.columns[-1]].apply(lambda x: codes[x].replace(' ','_'))

trn[:5]

"""Once confirmed all labels doesnot contain space move forward"""

fnames= get_image_files(path_img)
fnames[:3]

img_f = fnames[0]
img=open_image(img_f)
img.show(figsize=(5,5))

src_size = min(img.size)

size=src_size//2
bs=4

trnList = ImageList.from_df(df=trn, path=path)
valList = ImageList.from_df(df=val, path=path)
tstList = ImageList.from_df(df=tst, path=path)

src = (ImageList.from_folder(path).split_by_list(trnList,valList).label_from_df())

"""To know more about the above steps see [this](https://docs.fast.ai/data_block.html#ItemList.label_from_df) because it would take lot to explain everything so linking to docs of fastai"""

data = (src.transform(get_transforms(),size=size).databunch(bs=bs).normalize(imagenet_stats))

data.show_batch(4, figsize=(10,7))

data.show_batch(4,figsize=(10,7),ds_type=DatasetType.Valid)

metrics=accuracy

learn=cnn_learner(data,models.resnet34,metrics=metrics)

"""Downloaded pretrained weights and using resnet34 which is trained on imagenet. You can try vgg, resnet50 also. Resnet 50 is best and can get better accuracy, I am not doing it, because of my space and time limitation"""

lr_find(learn)
learn.recorder.plot()

lr=3e-3

learn.fit_one_cycle(10, slice(lr), pct_start=0.9)

learn.save('stage-1')

"""This is very important step since if wanting to experiment with different learning rate and other hyperparametes, its important to save so that we can load when needed"""

learn.load('stage-1')

learn.show_results(rows=4,figsize=(8,9))

"""This step is important since it shows which images we have correctly classified and which we did not"""

learn.unfreeze()

"""Unfreezes entire model, sets every layer group to train."""

lrs= slice(lr/400,lr/4)

learn.fit_one_cycle(12,lrs,pct_start=0.8)

learn.save('stage-2')

"""As you can see accuracy has increased compared to stage 1 so save this"""

learn.show_results(ds_type=DatasetType.Valid, rows=4,figsize=(8,9))

learn.export()

src2 = (ImageList.from_folder(path)
       .split_by_list(trnList, tstList)
       .label_from_df()
       )
data2 = (src2.transform(get_transforms(), size=size)
        .databunch(bs=bs)
        .normalize(imagenet_stats))

learn2 = cnn_learner(data2, models.resnet34, metrics=metrics)
learn2.load('stage-2');

preds,y,losses = learn2.get_preds(with_loss=True)
accuracy(preds,y)

len(trn), len(val),len(tst)

bs = 8
size = src_size
metrics=accuracy

src3 = (ImageList.from_df(df=trn.append(tst, ignore_index=True), path=path)
       .split_by_rand_pct(valid_pct=0.2, seed=42)
       .label_from_df()
       )
data3 = (src3.transform(get_transforms(), size=size)
        .databunch(bs=bs)
        .normalize(imagenet_stats))

learn = cnn_learner(data3, models.resnet34, metrics=metrics)

learn.load('stage-2')

learn.unfreeze()

lr_find(learn)
learn.recorder.plot()

lr=5e-4

lrs=slice(1e-5,lr/10)

learn.fit_one_cycle(10,lrs)

learn.save('stage-3')

learn.export()

src2 = (ImageList.from_folder(path)
       .split_by_list(trnList, valList)
       .label_from_df()
       )
data2 = (src2.transform(get_transforms(), size=size)
        .databunch(bs=bs)
        .normalize(imagenet_stats))

learn2 = cnn_learner(data2, models.resnet34, metrics=metrics)
learn2.load('stage-3');

preds,y,losses = learn2.get_preds(with_loss=True)
accuracy(preds,y)

"""I got accuracy of 97.84%"""